# Generated by Django 3.0.5 on 2021-04-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210422_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Payment Success', 'Payment Success'), ('On Working', 'On Working'), ('Complete', 'Complete')], max_length=200, null=True),
        ),
    ]
