# Generated by Django 3.0.5 on 2021-04-26 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_shippingaddress_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
