# Generated by Django 3.0.5 on 2021-04-27 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_customer_certifier_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='certifier_user_id',
        ),
    ]
